/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { CIMObject } from "../CIMObject";
import { LabelFeatureType } from "./LabelFeatureType";

/**
 * Standard label engine feature weights.
 *
 */
export type StandardFeatureWeight = 0 | 1 | 2 | 3;
/**
 * Standard label engine label weight.
 *
 */
export type StandardLabelWeight = 0 | 1 | 2;
/**
 * Standard label engine number of labels options.
 *
 */
export type StandardNumLabelsOption = 0 | 1 | 2 | 3;
/**
 * Standard label engine point placement methods.
 *
 */
export type StandardPointPlacementMethod = 0 | 1 | 2 | 3;
/**
 * Standard label engine label rotation types.
 *
 */
export type StandardLabelRotationType = 0 | 1 | 2 | 3;
/**
 * Standard label engine polygon placement methods.
 *
 */
export type StandardPolygonPlacementMethod = 0 | 1 | 2;

/**
 * Represents standard label engine label placement properties.
 *
 */
export type CIMStandardLabelPlacementProperties = CIMObject & {
  /**
   * Gets or sets the feature type being labeled.
   */
  featureType?: LabelFeatureType;
  /**
   * Gets or sets the feature weight.
   */
  featureWeight?: StandardFeatureWeight;
  /**
   * Gets or sets the label weight.
   */
  labelWeight?: StandardLabelWeight;
  /**
   * Gets or sets the option for number of labels.
   */
  numLabelsOption?: StandardNumLabelsOption | string;
  /**
   * Gets or sets the line label position.
   */
  lineLabelPosition?: null | CIMStandardLineLabelPosition;
  /**
   * Gets or sets the line label priorities.
   */
  lineLabelPriorities?: null | CIMStandardLineLabelPriorities;
  /**
   * Gets or sets the point placement method.
   */
  pointPlacementMethod?: StandardPointPlacementMethod | string;
  /**
   * Gets or sets the point placement priorities.
   */
  pointPlacementPriorities?: null | CIMStandardPointPlacementPriorities;
  /**
   * Gets or sets an array of point placement angles.
   */
  pointPlacementAngles?: number[] | null;
  /**
   * Gets or sets the buffer ratio.
   */
  bufferRatio?: number;
  /**
   * Gets or sets the line offset.
   */
  lineOffset?: number;
  /**
   * Gets or sets the maximum distance from target.
   */
  maxDistanceFromTarget?: number;
  /**
   * Gets or sets the rotation type.
   */
  rotationType?: StandardLabelRotationType;
  /**
   * Gets or sets the rotation field.
   */
  rotationField?: null | string;
  /**
   * Gets or sets a value indicating whether or not to place the label perpendicular to the angle.
   */
  perpendicularToAngle?: boolean;
  /**
   * Gets or sets the polygon placement method.
   */
  polygonPlacementMethod?: StandardPolygonPlacementMethod;
  /**
   * Gets or sets a value indicating whether or not to place the label only inside a polygon.
   */
  placeOnlyInsidePolygon?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow overlapping labels.
   */
  allowOverlappingLabels?: boolean;
};
/**
 * Represents standard label engine line label position.
 *
 */
export interface CIMStandardLineLabelPosition {
  /**
   * Gets or sets a value indicating whether or not to produce curved labels.
   */
  produceCurvedLabels?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement above lines.
   */
  above?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement below lines.
   */
  below?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement on top of lines.
   */
  onTop?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement to the left of the line.
   */
  left?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement to the right of the line.
   */
  right?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow along lines at the best position.
   */
  inLine?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement at the start of lines.
   */
  atStart?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement at the end of lines.
   */
  atEnd?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement parallel to lines.
   */
  parallel?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement perpendicular to lines.
   */
  perpendicular?: boolean;
  /**
   * Gets or sets a value indicating whether or not to allow placement horizontally.
   */
  horizontal?: boolean;
  /**
   * Gets or sets a the offset from the line.
   */
  offset?: number;
}
/**
 * Represents standard label engine line label priorities.
 *
 */
export interface CIMStandardLineLabelPriorities {
  /**
   * Gets or sets a the label position priority for above and before the line.
   */
  aboveBefore?: number;
  /**
   * Gets or sets a the label position priority for above and at the start of the line.
   */
  aboveStart?: number;
  /**
   * Gets or sets a the label position priority for above and along the line.
   */
  aboveAlong?: number;
  /**
   * Gets or sets a the label position priority for above and at the end of the line.
   */
  aboveEnd?: number;
  /**
   * Gets or sets a the label position priority for above and after the line.
   */
  aboveAfter?: number;
  /**
   * Gets or sets a the label position priority for centered and before the line.
   */
  centerBefore?: number;
  /**
   * Gets or sets a the label position priority for centered and at the start of the line.
   */
  centerStart?: number;
  /**
   * Gets or sets a the label position priority for centered and along the line.
   */
  centerAlong?: number;
  /**
   * Gets or sets a the label position priority for centered and at the end of the line.
   */
  centerEnd?: number;
  /**
   * Gets or sets a the label position priority for centered and after the line.
   */
  centerAfter?: number;
  /**
   * Gets or sets a the label position priority for below and before the line.
   */
  belowBefore?: number;
  /**
   * Gets or sets a the label position priority for below and at the start of the line.
   */
  belowStart?: number;
  /**
   * Gets or sets a the label position priority for below and along the line.
   */
  belowAlong?: number;
  /**
   * Gets or sets a the label position priority for below and at the end of the line.
   */
  belowEnd?: number;
  /**
   * Gets or sets a the label position priority for below and after the line.
   */
  belowAfter?: number;
}
/**
 * Represents standard label engine point placement priorities.
 *
 */
export interface CIMStandardPointPlacementPriorities {
  /**
   * Gets or sets a the label position priority for the above left position.
   */
  aboveLeft?: number;
  /**
   * Gets or sets a the label position priority for the above center position.
   */
  aboveCenter?: number;
  /**
   * Gets or sets a the label position priority for the above right position.
   */
  aboveRight?: number;
  /**
   * Gets or sets a the label position priority for the center left position.
   */
  centerLeft?: number;
  /**
   * Gets or sets a the label position priority for the center right position.
   */
  centerRight?: number;
  /**
   * Gets or sets a the label position priority for the below left position.
   */
  belowLeft?: number;
  /**
   * Gets or sets a the label position priority for the below center position.
   */
  belowCenter?: number;
  /**
   * Gets or sets a the label position priority for the below right position.
   */
  belowRight?: number;
}
